/**
 * Centralized z-index scale for the entire app.
 * Always use these constants instead of hardcoded numbers.
 *
 * Scale overview (low → high):
 *   STARFIELD → BASE → TOPBAR_INNER → ELEMENT_OVERLAY → TERMINAL_SEARCH
 *   → FIND_BAR → AI_BACKDROP → TOOLBAR → WIKILINK_MENU → MENU_BACKDROP
 *   → DROPDOWN → CONTEXT_BACKDROP → CONTEXT_MENU → SETTINGS → DROP_ZONE
 *   → LIGHTBOX → OVERLAY → CALLOUT_BACKDROP → TOAST → FIRST_SYNC → ERROR_BOUNDARY
 */

export const Z = {
  STARFIELD: 0,
  BASE: 1,
  TOPBAR_INNER: 2,
  ELEMENT_OVERLAY: 5,
  TERMINAL_SEARCH: 10,
  FIND_BAR: 50,
  AI_BACKDROP: 99,
  TOOLBAR: 100,
  WIKILINK_MENU: 110,
  MENU_BACKDROP: 199,
  DROPDOWN: 200,
  DROPDOWN_TOP: 201,
  CONTEXT_BACKDROP: 250,
  CONTEXT_MENU: 300,
  SETTINGS: 400,
  SETTINGS_INNER: 401,
  DROP_ZONE: 998,
  TERMINAL_TAB: 1000,
  LIGHTBOX: 1100,
  OVERLAY: 1200,
  CALLOUT_BACKDROP: 9998,
  FAB: 9000,
  BOTTOM_SHEET_OVERLAY: 9500,
  BOTTOM_SHEET: 9501,
  TOAST: 9999,
  FIRST_SYNC: 10000,
  ERROR_BOUNDARY: 99999,
};
