import { useCallback, useEffect, useRef, useState } from "react";
import { DEFAULT_SORT_MODE, isSortMode } from "../utils/noteSort";

/** The chosen sort mode. */
const MODE_KEY = "boojy-note-sort";
/** noteId → epoch ms of the last time that note was opened. */
const OPENED_KEY = "boojy-note-opened";

const readMode = () => {
  try {
    const saved = localStorage.getItem(MODE_KEY);
    return isSortMode(saved) ? saved : DEFAULT_SORT_MODE;
  } catch {
    return DEFAULT_SORT_MODE;
  }
};

const readOpened = () => {
  try {
    const raw = JSON.parse(localStorage.getItem(OPENED_KEY));
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
    const out = {};
    for (const [id, ts] of Object.entries(raw)) {
      if (typeof ts === "number" && Number.isFinite(ts)) out[id] = ts;
    }
    return out;
  } catch {
    return {};
  }
};

/**
 * Owns the sidebar's ordering preference and the last-opened timestamps it
 * reads in recency mode.
 *
 * Both live in localStorage, never in the user's files: opening a note must not
 * touch anything on disk. The consequence is that recency is per-machine, and a
 * vault opened elsewhere regenerates note IDs and starts from the alphabetical
 * tail — the same caveat the note-ID index already carries.
 *
 * @param {Record<string, unknown>} noteData The live note store, used to prune.
 */
export function useNoteSort(noteData) {
  const [sortMode, setSortModeState] = useState(readMode);
  const [lastOpened, setLastOpened] = useState(readOpened);

  const setSortMode = useCallback((mode) => {
    if (!isSortMode(mode)) return;
    setSortModeState(mode);
    try {
      localStorage.setItem(MODE_KEY, mode);
    } catch {
      /* a full or blocked store just loses the preference on reload */
    }
  }, []);

  const markOpened = useCallback((id) => {
    if (!id) return;
    setLastOpened((prev) => ({ ...prev, [id]: Date.now() }));
  }, []);

  // Persist pruned against the live note list. Doing it here rather than in the
  // delete handlers means one rule covers deletions, files removed outside
  // Boojy, and IDs regenerated by a vault move — instead of three call sites
  // that each have to remember. The empty-store guard is load-bearing:
  // `noteData` is {} until notes finish loading, and writing then would erase
  // every timestamp on launch.
  const noteCount = Object.keys(noteData).length;
  const noteDataRef = useRef(noteData);
  noteDataRef.current = noteData;

  useEffect(() => {
    if (noteCount === 0) return;
    const timer = setTimeout(() => {
      const live = noteDataRef.current;
      const pruned = {};
      for (const [id, ts] of Object.entries(lastOpened)) {
        if (live[id]) pruned[id] = ts;
      }
      try {
        localStorage.setItem(OPENED_KEY, JSON.stringify(pruned));
      } catch {
        /* non-critical: recency degrades to the alphabetical tail next launch */
      }
    }, 300);
    return () => clearTimeout(timer);
  }, [lastOpened, noteCount]);

  return { sortMode, setSortMode, lastOpened, markOpened };
}
